Create get_relation_history
OSM-Catalan/monitorOSM pull request #2
Opened 2023-06-21 14:37 UTC by marcboschmatas

Creat funció per a obtenir la història d'una relació.

2023-06-21 15:09 UTC, jmaspons reviewed
Gràcies per l'aportació, pot ser molt útil!

De moment tot el paquet és en català, però aquesta funció és prou genèrica com perquè es pugui incorporar a un paquet pel públic general, així que de moment ja està bé.

2023-06-21 15:09 UTC, jmaspons commented on R/get_relation_history
> +    map(\(x)
Perquè serveix `\(x)`? No ho havia vist mai

2023-06-21 15:15 UTC, marcboschmatas commented on R/get_relation_history
> +    map(\(x)
És l'equivalent a ```function(x)``` per a funcions anònimes, des d'R 4.1 crec.

2023-06-21 15:16 UTC, marcboschmatas commented
Bones, per part meva perfecte els canvis que proposes. Caldrà provar que funcioni tot.

2023-06-21 15:16 UTC, marcboschmatas commented
D'altra banda, si pot agafar la història d'altres elements potser que li canviem el nom, no?

2023-06-21 15:23 UTC, marcboschmatas commented
Veig que no funciona amb coses que no siguin relacions. Hi segueixo treballant i faig una nova proposta quan tingui un sistema funcional

2023-06-22 08:41 UTC, jmaspons commented on R/get_relation_history
> +    map(\(x)
Ok. Si no és impressindible, usaria la forma clàssica. Altrament caldria augmentar la versió mínima d'R requerida al fitxer DESCRIPTION

2023-06-22 08:44 UTC, marcboschmatas commented on R/get_relation_history
> +    map(\(x)
Aleshores també hem de treure la pipe nativa ```|>```.

2023-06-22 10:12 UTC, jmaspons requested changes
Pots afegir l'extensió .R al fitxer? Aquesta tarda miro de fer proves i si tot va bé ja podrem fer el merge. Més endavant ja miraré d'afegir testos automàtics per aquesta funció i les altres

2023-06-22 10:12 UTC, jmaspons commented on R/get_osm_history
> +#1 @param osm_type string que especifica el tipus d'element ("node", "way" o "relation")
```suggestion
#' @param osm_type string que especifica el tipus d'element ("node", "way" o "relation")
```

2023-06-22 10:16 UTC, jmaspons commented
Ah, tb falta pujar el fitxer .Rd

2023-06-22 10:31 UTC, marcboschmatas commented
@jmaspons podries fer tu el fitxer .Rd, he treballat una mica en brut i no tinc el paquet en local.

2023-06-22 16:21 UTC, marcboschmatas commented
Bones! Doncs a veure, si no corre pressa ho aniré fent jo, i ja de pas
arreglo els errors del R CMD CHECK i faig la documentació i tot plegat.
També anem pensant com ho integrem amb la resta de funcions, que quan
detecti un canvi que no ens agrada retorni l'estat actual i l'anterior?

El dj., 22 de juny 2023, 18:12, Joan Maspons ***@***.***> va
escriure:

> Això ja fa bona pinta, @marcboschmatas <https://github.com/marcboschmatas>
> !
>
> Els errors de R CMD check i pre-commit són senzills d'arreglar. Ho vols
> fer tu o ho faig a posteriori?
>
> El que m'agradaria pensar bé són els formats de sortida. Potser seria
> millor que cada fila de les taules fos un sol conjunt de canvis (columnes
> osm_id, version, changeset, timestamp, user i user_id, com a clau
> primària de la taula + osm_type) i que cada etiqueta fos una columna.
> Pels membres de les relacions i vies, el mateix. És una mica estrany, però
> podem posar una columna de data.frames amb les propietats dels membres.
>
> Com ho veus? Vols provar-ho de fer tu o ho donem el PR per bo i ja afegiré
> els canvis més endavant?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OSM-Catalan/monitorOSM/pull/2#issuecomment-1602947164>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APKYMO45DUGRK3Y243KAQVDXMRVF5ANCNFSM6AAAAAAZO3OQ6E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-21 07:31 UTC, closed without merging